baseurl= "http://qiliu.co/"
languageCode= "en-EN"
title= "Qi Liu's Blog"
theme = "casper"
paginate = 5
disqusShortname = "YOUR_SHORT_NAME_HERE"
copyright = "All rights reserved - 2016"
canonifyurls = true

[params]
  description = "A tiny house"
  cover = "images/cover.jpg"
  author = "Qi Liu"
  # authorlocation = "Paris, France"
  authorwebsite = "http://qiliu.co"
  bio= "my bio"
  logo = "images/logo.png"
  # googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  github = "https://github.com/keithpurr"
  # twitter = "vjeantet"
  # facebook = "heng"
  linkedin = "https://www.linkedin.com/in/qi-liu-78866734"
  # instagram = "heng"
  # pinterest = "heng"
  # googleplus = "heng"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[[menu.main]]
  name = "My Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About"
  weight = -110
  identifier = "about"
  url = "/about"
